### PR TITLE
Join with 2nd Password disabled

### PR DESCRIPTION
**Pull request by johmarjac**
This PR adds possibilty to join the game without having 2nd password enabled.

### CODE REVIEW

**Comment by Skeatwin** [comment]
Approval for me :)

**Comment by Eastrall** [comment]
Nice! Everything looks good to me. Did you tried with a client that has the 2nd password disabled?
On a previous emulator, I had a problem regarding this system. If it works on a basic V15 client, we are good to merge! 😄

**Comment by johmarjac** [comment]
Yes, works perfectly fine! :)
https://puu.sh/BfkW0/935f864feb.mp4

**Comment by Eastrall** [comment]
Awesome! Let's merge then!

**Pull request merged**
